### PR TITLE
More Truffle examples - all now @ solc 0.5.0

### PR DESCRIPTION
**Pull request by gskapka**
### What this PR is:

Adding more of the Truffle-versioned examples for folk to download and run, showing them how to use our examples in a full-blown Truffle (5) environment, with testing and everything.

***

### To Do: 

__❍__  @riccardopersiani Please could you pull this then test _each_ of the examples in turn making sure the tests all pass for you too. The `jpgs` in each repo are from the tests passing on my machine, so ∴ should all pass for you too.

__❍__ Once you've done this, please report back an issues, suggestions for improvements, notes etc so I can deal with them, and then finally @D-Nice can merge.

***

### Notes: 

__❍__ Included in each of the example folders is a `jpg` of the passing tests on my machine, from fresh repo-pulls. These `jpgs` will appear correctly in the `README` once this PR is merged, but will yet not display properly in this PR due to wrong relative paths.

__❍__ Each folder is intended to be a stand-alone, download-able working example, hence each of them having their own versions of the `oraclizeAPI`, `archive.zip`'s and other such files.  I've not used symlinks to the actual API for this reason too.

__❍__ Full disclosure: Also making this PR & updates to test my split-ssh qube set up is working correctly!  :rofl:

### CODE REVIEW

**Comment by riccardopersiani** [comment]
### Outcome:

All the tests have been passed successfully once.

screenshot 2018-11-12 at 09 50 48

***

### Notes:

*MacOS*

@D-Nice @gskapka, I experienced some weird behaviours due probably to `npm`/`truffle`/`computation`/`engine`:

__❍__  after the first `npm install` a module was not installed;

image

__❍__  after approximately 5 mins, looks like the `ethereum-bridge` is kind of going down or not answering properly;

image

Maybe we should inform users about this potential behaviour...

__❍__  if a bunch of tests are done consecutively, something fails (probably the computation?).

**Comment by gskapka** [comment]
So the URL-Requests always runs through cleanly the first time, and then one or occasionally two tests fail on a subsequent run (if done immediately after) due to the computation itself not returning the correct thing. If instead you wait a while, the test-suite runs through cleanly again. 

I had no idea why but didn't look into debugging it too hard since the tests work on the Truffle/Bridge side of things and pass as they ought.

Re the `npm` thing, that's a local issue and nothing to do with the repo. 

***

### To do @riccardopersiani 

Per the original request, could you please run _all_ the truffle examples to make sure they _all_ work as expected on MacOS?

**Comment by D-Nice** [comment]
Even the example contract files could be symlinked to the current master ones, helping with maintainability if they need to be updated (albeit maybe not the smartest thing to do now with 0.5 out, since we'll probably want to make thes ones in master compatible with 0.5, not sure how compatible your truffle integrations are going to be with those upon update?).

**Comment by gskapka** [comment]
Will work on the API update to 0.5 first then rebase this PR on it to make it work with the latest versions.

Re symlinking the API - should be no issue, however I didn't do so since I wanted the truffle examples here to stand alone/be truffle-boxable in future. Because these Oraclize examples are an entry-point for many people _new_ to smart-contracts I wanted the truffle versions to be as self-contained as possible, and as _simple_ as possible, which using sub-modules would kind of go against.

There's also the issue of the symlinks not working on windows machines...? Note also that the example contracts inside these new truffle ones are also updated to current best practices (`emit` keyword etc) and are _not_ the same as the contracts in the base repo for that reason.

***

So thoughts going forward @D-Nice & @riccardopersiani? 

__Option 1)__ Do we keep these as stand-alone? It's more work to maintain (though hardly since these will be semver locked to working versions of everything) 

__Option 2)__ Or do we update the contracts in the main repo to be as current as possible (once the API is current) and then symlink everything in the truffle versions?

**Comment by D-Nice** [comment]
Yes, you're correct about the Windows incompatibility, which slipped my mind yesterday, and I was going to mention today. I think that may make it a deal-breaker, so let's stick with the stand-alone philosophy. But a script to replace duplicate files from root would help with maintanability.

**Comment by gskapka** [comment]
Stand-alone with some automation it is then!

**Comment by riccardopersiani** [comment]
✅ I tested every example successfully and checked every image in the corresponding README.md.

**Comment by gskapka** [comment]
## Update: 

:heavy_check_mark: Script added to copy examples from the root of the repo to the correct places in the truffle examples dir. 

:black_nib: __NOTE:__ Of course if you run this script once this branch has been merged the truffle tests won't pass anymore due to the examples currently being sat at `solc <= 0.5.0`. However, I've made a branch to PR that updates the remainder of the repo to the new compiler version once this PR is merged.

***

@D-Nice Can you give this a quick glance as I think it's ready to merge.

**Comment by D-Nice** [comment]
LGTM

All the new truffle examples will target 0.5 then. Is it more appropriate to wait for this PR https://github.com/oraclize/ethereum-api/pull/67 to be resolved and merged, so that any changes to it can be reflected for the examples before we merge? Other than that point, it appears good and ready to merge.

**Comment by D-Nice** [comment]
Yes, tagging it is a good call, allowing for those needing to refer to older versions.

**Comment by D-Nice** [comment]
tagged current master https://github.com/oraclize/ethereum-examples/releases/tag/solc-0.4.x

**Comment by D-Nice** [comment]
Merging

**Comment by D-Nice** [comment]
@gskapka delete the branch once able/deemed unnecessary

**Pull request merged**
